### ISSUE TITLE
A question about experimental results

### ISSUE THREAD

**Issue by speedcell4** [INK-USC/TriggerNER#11]
Hi, thanks for sharing your source code.

I have a question about the experimental results. If you use 100% sentences labeled with both entity tags and trigger
tags, what the performance will be?

**Comment by speedcell4** [comment]
sorry, mistakenly clicked the "Close issue" button

**Comment by danny911kr** [comment]
Hi, @speedcell4 
Thank you for your question.

We couldn't conduct experiments using more than 20% of sentences labeled with both entity tags and trigger tags due to annotation cost.
From our F1 curve, we could expect that using both entity tags and trigger tags will have better performance than just only using entity tags.

However, at the end like 100% sentences labeled with both entity tags and trigger tags, 
we think the improvement might be very marginal since the NER model still affects a lot from entity coverage.
We argue that this model is more useful in a low-resource NER environment.

**Comment by speedcell4** [comment]
Thank you for your response~
