### ISSUE TITLE
Question about the inconsistency between the paper and the code

### ISSUE THREAD

**Issue by longlongman** [INK-USC/TriggerNER#12]
I have a question about the inconsistency between the paper and the code:

1. In section 3.2, the paper saying "Note that the BLSTM used in the TrigEncoder and TrigMatcher modules is the same BLSTM we use in the SeqTagger to obtain H", however, I check the code in https://github.com/INK-USC/TriggerNER/blob/c38df9333c407afed6a189a6f7061d4601af22a4/supervised.py#L83-L94 https://github.com/INK-USC/TriggerNER/blob/c38df9333c407afed6a189a6f7061d4601af22a4/model/soft_inferencer.py#L19-L29 https://github.com/INK-USC/TriggerNER/blob/c38df9333c407afed6a189a6f7061d4601af22a4/model/soft_inferencer.py#L45-L57 I believe that the BLSTM in SeqTagger is not the same with BLSTM in TrigEncoder and TrigMatcher. While training the SeqTagger, the H(output) is from a specific BLSTM in SeqTagger, nothing to do with the BLSTM in TrigEncoder and TrigMatcher. I can not agree with what you say in the paper and it really confuses me.

**Comment by danny911kr** [comment]
Hi, @longlongman,
Thank you for your question.

That sentence means that the **structure** of BLSTM used in the TrigEncoder and TrigMatcher modules is the same **structure** of BLSTM we used in the SeqTagger to obtain H, instead of the **weights**.

Sorry for the confusion.
We will clarify this point in the next arXiv version.
Thank you for pointing out this.
