### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wjczf123** [INK-USC/TriggerNER#8]
I run your new code. It seems that percentage also doesn't work in semi_supervised.py.
I run: python semi_supervised.py --device cuda:0 --dataset CONLL --percentage 20, test result F1 is 85.58.
I run: python semi_supervised.py --device cuda:1 --dataset CONLL --percentage 3, test result F1 is 86.39.

**Comment by wjczf123** [comment]
And what is the setting of argument --unlabeled_percentage?
Can we reproduce your experiment with the default settings(unlabeled_percentage = 0.8)?
I hope you can carefully check the results to ensure that the results can be reproduced.

**Comment by danny911kr** [comment]
Hi @wjczf123,

Thanks for pointing it out. There was an issue with reading trigger files.  I think you can reproduce the results this time.
Please note that, `--percentage 15` is 3% of the original training dataset since the trigger file is already 20% of the original training dataset.

`--unlabeled_percentage` is the amount of unlabeled data we want to use for semi-supervised learning.
In more specific, in our experiment setting, we use 20% of the original training dataset as a training data, and rest 80% of the original training data as an unlabeled data.
That’s why the current default value of the argument is 0.8.

Appreciate it again for your active feedback.

**Comment by wjczf123** [comment]
OK. Thank u a lot.
